epochs: 2000
batch_size: 20
n_landmarks: 10
color_jitter: True
dataset: 50salads
dataset_path: '/scratch/ssd001/home/winstonc/50salads-n_pairs=None-mse=30.00-action_pair=None'
n_training_max: 50000 #max number of training examples to use
save_path: '/scratch/hdd001/home/winstonc/logs/dundar_50salads-10pts'
fixed_covar: 0.008
flip_probability: 0.5
img_size: 128
learning_rate: 0.0001
model: PartFactorizedModel
n_filters: 32
n_layers_D: 3
naf: 0
ndf: 64
ngc: 64
nsf: 6
no_grad_clip: True
no_lsgan: False
num_D: 2
num_workers: 8
reduced_w: True
resume_ckpt:
resume_ckpt_D:
resume_ckpt_opt_G:  # optimizer checkpoint for main model
resume_ckpt_opt_D:  # optimizer checkpoint for discriminator
rot_lb: -0.5
rot_ub: 0.5
scale_lb: 0.85
scale_ub: 1.15
torch_home: '' # set this to where you want your vgg weights to be saved
trans_lb: -20
trans_ub: 20
use_gan: False
use_identity_covariance: False
fixed_covar: 0.008
use_vgg: True
use_warped: True # warping augmentating during training
use_fg_bg_mask: True # use foreground-background separation masks
val_frac: 0.0003
val_freq: 50
vgg_lambda: 5.0
